import type { Metadata } from 'next'
import Navbar from '../Components/Navbar/Navbar';
import { Poppins } from "next/font/google";
import ScrollToTopButton from "@/Components/button/Scrollbutton";
import { StartTop } from "@/Components/starttotop/StartTop";








const pop = Poppins({ subsets: ['latin'],
  weight: ['400', '700'],
});
import './globals.css'
import Footer from '../Components/Footer';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={pop.className}>
      <StartTop/>
      <Navbar />
      {children}
      <ScrollToTopButton/>
      <Footer />
      </body>
    </html>
  )
}
